name: Build and Run NPM Package

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Remote Repository
        uses: actions/checkout@v3

      - name: Clone RDF toolkit
        run: git clone https://github.com/ektrah/rdf-toolkit

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        working-directory: rdf-toolkit
        run: |
          npm ci

      - name: Build NPM Package
        working-directory: rdf-toolkit
        run: |
          npm run build
          npm i @rdf-toolkit/cli

      - name: Copy ontologies
        run: cp ontologies/*.ttl rdf-toolkit/explorer/vocab

      - name: Build site
        working-directory: rdf-toolkit/explorer
        run: npx rdf make site

      - name: Commit Built Files
        run: |
          cp -r rdf-toolkit/explorer/public html.explorer
          git config user.name "GitHub Action"
          git config user.email "github-action@example.com"
          git add html.explorer
          git commit -m "Commit built files"
          git push
